service: outcomesai-drchrono-http

frameworkVersion: '3'

plugins:
  - serverless-prune-plugin

custom:
  config: ${file(../../lambda_config/outcomesai-${self:provider.stage}-config.json)}
  prune:
    automatic: true
    number: 3
    dryRun: false
    olderThan: 7

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  deploymentBucket: outcomesai-${opt:stage}
  logRetentionInDays: 3
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
        - '*'

functions:
  http:
    name: ${self:service}-${self:provider.stage}
    handler: handler.lambda_handler
    description: Handles HTTP GET requests to drchrono API.
    memorySize: 1024
    timeout: 90
