INSERT INTO administration_routes (id, name, description, status) VALUES
(1, 'Oral', 'Medication is taken through the mouth and swallowed, commonly used for tablets, capsules, liquids, etc.', 'Active'),
(2, 'Topical', 'Medication is applied directly to a particular area of skin.', 'Active'),
(3, 'Inhalation', 'Medication is taken in through the lungs via devices like inhalers.', 'Active'),
(4, 'Nasal', 'Medication is administered into the nose, often as sprays or drops.', 'Active'),
(5, 'Rectal', 'Medication is administered via the rectum, often as suppositories.', 'Active'),
(6, 'Subcutaneous', 'Administration into the layer of skin directly below the dermis and epidermis, collectively referred to as the cutis.', 'Active'),
(7, 'Intramuscular', 'Administration into the muscular tissue, often into larger muscles of the body.', 'Active'),
(8, 'Intravenous', 'Administration directly into the bloodstream via a vein.', 'Active'),
(9, 'Sublingual/Buccal', 'Medication is placed under the tongue (sublingual) or between the cheek and gum (buccal) and allowed to dissolve.', 'Active'),
(10, 'Ophthalmic', 'Medication is administered to the eyes, often as drops or ointments.', 'Active'),
(11, 'Otic', 'Medication is administered to the ears, often as drops.', 'Active'),
(12, 'Transdermal', 'Medication is absorbed through the skin, often through medicated patches.', 'Active'),
(13, 'Vaginal', 'Medication is administered into the vagina, often as creams, gels, or suppositories.', 'Active'),
(14, 'Intra-articular', 'Medication is injected directly into a joint.', 'Active'),
(15, 'Intrathecal', 'Medication is injected into the spinal canal.', 'Active'),
(16, 'Intradermal', 'Medication is injected just below the surface of the skin.', 'Active'),
(17, 'Intraperitoneal', 'Medication is delivered into the peritoneal cavity (abdomen).', 'Active'),
(18, 'Epidural', 'Medication is delivered into the epidural space of the spine.', 'Active'),
(19, 'Enteral', 'Medication is introduced directly into the intestines, as in a feeding tube.', 'Active');