INSERT INTO dosage_forms (id, name, description, status) VALUES
(1, 'Tablet', 'A solid medicinal dosage form in which active ingredients are compressed into a solid, round, or oval shape.', 'Active'),
(2, 'Capsule', 'A cylindrical, two-piece medicinal dosage form made of a gelatin or similar material that encloses a drug in either a solid or liquid form.', 'Active'),
(3, 'Liquid', 'Any preparation in a liquid form that is intended for oral, topical, or injectable use. This includes solutions, syrups, suspensions, or emulsions.', 'Active'),
(4, 'Caplet', 'A smooth, coated, oval-shaped medicinal tablet designed to make swallowing easier.', 'Active'),
(5, 'Lozenge', 'A small, flavored medicinal tablet or disk that dissolves in the mouth, often used to provide local relief in the mouth or throat.', 'Active'),
(6, 'Gel', 'A semi-solid, jelly-like consistency medication form, often used for topical application or sometimes orally.', 'Active'),
(7, 'Ointment', 'A semi-solid preparation, typically greasy in nature, intended for topical application to the skin or mucous membranes.', 'Active'),
(8, 'Cream', 'A semi-solid emulsion of oil and water, used topically on the skin or mucous membranes.', 'Active'),
(9, 'Inhaler', 'A device containing medication that is inhaled into the lungs. Often used for conditions like asthma or COPD.', 'Active'),
(10, 'Patch', 'A medicated adhesive patch that is placed on the skin to deliver a time-released dose of medication through the skin.', 'Active'),
(11, 'Suppository', 'A solid dosage form that is inserted into a body orifice, such as the rectum or vagina, where it dissolves and releases the medication.', 'Active'),
(12, 'Spray', 'A liquid medication that is dispensed in mist form and might be used nasally, orally, or topically.', 'Active'),
(13, 'Injection', 'A liquid medication delivered via a syringe and needle, intended for various administration routes such as intramuscular, subcutaneous, or intravenous use.', 'Active'),
(14, 'Drops', 'A liquid medication intended to be administered drop by drop, such as eye drops or ear drops.', 'Active'),
(15, 'Wafer', 'Thin, dissolvable discs that are placed in the mouth and dissolve to release medication.', 'Active'),
(16, 'Lotion', 'A liquid preparation for external application, typically less thick than creams or ointments.', 'Active'),
(17, 'Softgel Capsules', 'Gelatin-based shells surrounding a liquid or semi-solid center. They are easier to swallow than regular capsules and can mask unpleasant tastes.', 'Active'),
(18, 'Effervescent Tablets', 'Tablets intended to be dissolved in water to release carbon dioxide, producing a bubbly solution for oral administration.', 'Active'),
(19, 'Solution', 'A liquid mixture in which the minor component (the solute) is uniformly distributed within the major component (the solvent).', 'Active'),
(20, 'Infusion', 'A process or period in which a substance, especially a drug, is slowly introduced into the body through a vein, typically using a drip.', 'Active'),
(21, 'Film', 'A thin layer or strip that dissolves when placed on the tongue or in the mouth.', 'Active'),
(22, 'Pellet', 'A small, rounded or cylindrical material, typically compressed, that can be swallowed or inserted into a body cavity.', 'Active'),
(23, 'Implant', 'A device or medication that is inserted or implanted, such as birth control implants.', 'Active'),
(24, 'Emulsion', 'A preparation of two non-mixing liquids, such as oil and water, where one liquid contains a dispersion of the other.', 'Active'),
(25, 'Granule', 'Small, often sugar-coated beads or grains, which can contain medication. They can be sprinkled onto food or into drinks.', 'Active'),
(26, 'Powder', 'Medication in a dried, powdered form that might be taken orally, applied topically, or used to make solutions/suspensions.', 'Active'),
(27, 'Foam', 'A frothy preparation used mainly for topical administration, often for dermatological conditions.', 'Active'),
(28, 'Gum', 'Chewable gum that delivers medication when chewed.', 'Active');

