/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export default {
  REGION: 'us-west-2', // your AWS region
  USER_POOL_ID: 'us-west-2_ACDESnb1G', // your Cognito User Pool ID
  USER_POOL_APP_CLIENT_ID: 'uh5cd9hjpuvp48sbkgpd5ls4b', // your Cognito User Pool Client ID
};
