/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsConfig = {
  Auth: {
    region: 'us-west-2', // Your AWS region
    userPoolId: 'us-west-2_ACDESnb1G', // Your Cognito User Pool ID
    userPoolWebClientId: 'uh5cd9hjpuvp48sbkgpd5ls4b', // Your Cognito User Pool Client ID
    oauth: {
      domain: 'https://outcomesai-api.auth.us-west-2.amazoncognito.com',
      scope: ['email', 'openid', 'phone'],
      redirectSignIn: 'https://outcomesai.com',
      redirectSignOut: 'https://outcomesai.com',
      responseType: 'code',
    },
  },
};

export default awsConfig;
