service: outcomesai-drchrono-medications

frameworkVersion: '3'

plugins:
  - serverless-prune-plugin

custom:
  dynamodbTableName: outcomesai_drchrono_medications_${self:provider.stage}
  config: ${file(../../../lambda_config/outcomesai-${self:provider.stage}-dynamodb-config.json)}
  prune:
    automatic: true
    number: 3
    dryRun: false
    olderThan: 7

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  deploymentBucket: outcomesai-${opt:stage}
  logRetentionInDays: 3
  iam:
    role: ${self:custom.config.iamRole}
  vpc:
    securityGroupIds: ${self:custom.config.securityGroupIds}
    subnetIds: ${self:custom.config.subnets}

resources:
  Resources:
    medicationsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.dynamodbTableName}
        AttributeDefinitions:
          - AttributeName: practice_id
            AttributeType: N
          - AttributeName: id
            AttributeType: N
          - AttributeName: patient
            AttributeType: N
        KeySchema:
          - AttributeName: practice_id
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: practice_id_patient
            KeySchema:
              - AttributeName: practice_id
                KeyType: HASH
              - AttributeName: patient
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true

package:
  include:
    - ../../../lambda_libs/drchrono/drchrono_api.py
    - ../../../lambda_libs/aws/dynamodb.py
    - ../../../lambda_libs/aws/parameter_store.py
    - ../../../lambda_libs/aws/secrets_manager.py
    - ../../../lambda_libs/aws/error_handling.py
    - ../../../lambda_libs/day_parts.py

functions:
  DrChronoAPI:
    name: ${self:service}-${self:provider.stage}
    handler: handler.lambda_handler
    description:
      Performs HTTP GET request on DrChrono medications api and saves items to
      Dynamodb outcomesai_drchrono_medications table.
    memorySize: 1024
    timeout: 90
